# Generated by Django 5.2.4 on 2025-08-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_alter_horario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='orden',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
