# Generated by Django 5.2.4 on 2025-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_horario_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='orden',
            field=models.IntegerField(),
        ),
    ]
