# Generated by Django 5.2.4 on 2025-08-04 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_horario_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'verbose_name': 'Jornada Laboral', 'verbose_name_plural': 'Jornadas Laborales'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='horario',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='turno',
            name='horarios',
            field=models.ManyToManyField(related_name='turnos', to='contabilidad.horario'),
        ),
    ]
