# Generated by Django 5.2.4 on 2025-08-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_jornada_options_remove_turno_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='orden',
            field=models.IntegerField(editable=False),
        ),
    ]
